(part "SMV1247-040LF"
    (packageRef "SMS7630040LF")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Manufacturer_Name" "Skyworks")
    (property "Manufacturer_Part_Number" "SMV1247-040LF")
    (property "Mouser_Part_Number" "873-SMV1247-040LF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Skyworks-Solutions-Inc/SMV1247-040LF?qs=WMHGlxXAKT%252B1FC3XWlqMng%3D%3D")
    (property "Arrow_Part_Number" "SMV1247-040LF")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/smv1247-040lf/skyworks-solutions?utm_currency=USD&region=nac")
    (property "Description" "Varactor Diodes Ls.45nH SOD-882 Single")
    (property "Datasheet_Link" "https://www.digikey.ph/en/products/detail/skyworks-solutions-inc/SMV1247-040LF/2770195")
    (property "symbolName1" "SMV1247-040LF")
)
